name: CI/CD for React App

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: List build directory
        run: ls -al build

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensures that the deploy job runs only after the build job is successful

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build

      - name: List downloaded build artifact
        run: ls -al build

      - name: Copy Files via SCP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}  # Directly use the PEM key from GitHub Secrets
          source: "build/*"
          target: "/var/www/html/"
          debug: true

      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}  # Directly use the PEM key from GitHub Secrets
          script: sudo systemctl restart nginx
