name: CI/CD for React App

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: List build directory
        run: ls -al build

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: build
          retention-days: 1
        timeout-minutes: 15  # Increased timeout for upload

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build-artifact
          path: build
        timeout-minutes: 15

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: build

      - name: Debug SSH connection
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "Debugging SSH connection..."
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no -vvv -i ~/.ssh/id_rsa $USER@$HOST echo "SSH connection successful"

      - name: Manual SCP File Transfer
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "Attempting manual SCP file transfer..."
          scp -o StrictHostKeyChecking=no -vvv -i ~/.ssh/id_rsa -r build/* $USER@$HOST:/var/www/html/
          echo "SCP completed"

      - name: Verify File Transfer
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "Verifying file transfer..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER@$HOST ls -R /var/www/html/

      - name: Restart Nginx
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "Restarting Nginx..."
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa $USER@$HOST sudo systemctl restart nginx
          echo "Nginx restarted"