name: CI/CD for React App

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the React app
        run: npm run build

      - name: Archive build output
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Decode PEM Key
        run: echo "${{ secrets.EC2_KEY }}" | base64 --decode > /tmp/your-key.pem

      - name: Copy Files via SCP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: /tmp/your-key.pem
          source: "build/*"
          target: "/var/www/html/"
          debug: true

      - name: Restart Nginx
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: /tmp/your-key.pem
          script: sudo systemctl restart nginx
